### ISSUE TITLE
Log out problem

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#133] opened 2015-06-01 10:49 UTC
When 'log out' is clicked in ODN/IC, user is logged out from ODN/IC and ODN/MidPoint (user remains logged in in ODN/UV).
When 'log out' is clicked in ODN/UV, user is logged out from ODN/UV and ODN/MidPoint (user remains logged in in ODN/IC).
When 'log out' is clicked in ODN/MidPoint, user is logged out from ODN/MidPoint (user remains logged in in ODN/UV and ODN/IC).

TC ID: ODN-64

**Comment by skrchnavy** [comment] 2015-06-01 12:26
@OskarStoffan isn't this duplicate of #95 ?

**Comment by peterklimo** [comment] 2015-07-16 09:07
there is only problem open from this bug report: IC/CKAN does not respond to logout notifications from other applications

**Comment by peterklimo** [comment] 2015-08-03 13:50
problem of the cas ckan extension, will be implemented by dominik kapisinsky

**Comment by mvi-eea-sk** [comment] 2015-08-25 08:12
@peterklimo implemented kapisinsky's changes into ckanext-odn-cas plugin

**Comment by peterklimo** [comment] 2015-09-03 09:02
@mvi-eea-sk please provide a reference in the repository to the fix

**Comment by peterklimo** [comment] 2015-09-03 09:11
related to https://team.eea.sk/jira/browse/COMSODE-1194

**Closed** 2015-09-28 15:27 UTC
Labels: priority: Urgent, severity: bug
