### ISSUE TITLE
Invalid URL for resource preview (public catalog)

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#79] opened 2015-04-01 13:24 UTC
In public catalog click to Organization. Choose dataset with resource. Click on resource. URL for resource at the top of form is invalid (EHttpDownload or LCatalog widget).
![url](https://cloud.githubusercontent.com/assets/10993265/6941849/759d136a-d883-11e4-9350-b67e9d586ceb.jpg)

TCID: ODN-111, ODN-35, ODN-23, ODN-104

**Comment by OskarStoffan** [comment] 2015-04-10 13:22
Similarly as #67 this should be related to not correctly set CKAN filestore

**Comment by mvi-eea-sk** [comment] 2015-04-16 07:34
@Jan-Marcek 
The L-FilesToCkan DPU needs CKAN filestore to be configured to function.
This DPU tries to upload dump to internal catalog and then is synchronized to public catalog.
Both catalogs need to be configured to use its filestore.

**Comment by skrchnavy** [comment] 2015-06-01 13:16
@eea71  isn't this duplicate of #119 ?

**Comment by Jan-Marcek** [comment] 2015-06-02 09:14
@mvi-eea-sk odn.storage.file.uri.template = http://$HOSTNAME/dump/{storage_id} from https://github.com/OpenDataNode/odn-box/blob/master/ckan-ic/production.ini#L144

**Comment by mvi-eea-sk** [comment] 2015-06-03 10:34
@Jan-Marcek but we do set it in internal catalog
because the url is synchronized from IC, there is a need to set it in IC not PC

**Comment by Jan-Marcek** [comment] 2015-06-03 10:55
Probably summer has impact on us :)
ic - odn.storage.file.uri.template is set  at - https://github.com/OpenDataNode/odn-box/blob/master/ckan-ic/production.ini#L144

pc - odn.storage.file.uri.template is NOT set  at -https://github.com/OpenDataNode/odn-box/blob/master/ckan-pc/production.ini

**Comment by mvi-eea-sk** [comment] 2015-06-05 11:51
@eea71 can you confirm this bug still occurs in release 1.0.2?
if not close this issue

**Comment by eea71** [comment] 2015-06-05 12:08
Seems now is ok...

**Comment by skrchnavy** [comment] 2015-06-05 12:25
@eea71 did it passed on v1.0.2 or v1.0.3 in preparation?

**Comment by eea71** [comment] 2015-06-05 12:32
in 1.0.2 version seems is ok..

**Closed** 2015-06-05 12:52 UTC
Labels: priority: Normal, severity: bug
