### ISSUE TITLE
odn-midpoint: Excessive logging

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#122] opened 2015-05-20 07:36 UTC
odn-midpoint creates a lot of logs. For example, it generated more than 500 MB of logs per 1 day on my ODN 1.0.1 server using odn-simple 1.0.1 Debian package. Reducing the volume of logs would be appreciated. For example, the default log level can be set higher than `TRACE`.

**Comment by skrchnavy** [comment] 2015-05-20 07:58
depends on OpenDataNode/odn-box#20

**Comment by Jan-Marcek** [comment] 2015-05-20 12:24
it was fixed by https://github.com/OpenDataNode/odn-box/blob/develop/midpoint/conf/web.xml#L92

It was caused by the fact that we were using snapshot version of midpoint.

**Comment by Jan-Marcek** [comment] 2015-05-21 13:08
not fixed. Not enough.

**Comment by Jan-Marcek** [comment] 2015-05-21 13:43
fixed by https://github.com/OpenDataNode/odn-box/commit/916b60121eaa23e1a6925e2663bad90a5b5afcc1

**Closed by Jan-Marcek** 2015-05-21 13:43 UTC
Labels: priority: Normal, severity: enhancement, status: in progress
