### ISSUE TITLE
Rest API resource problems (ODN/IC and ODN/PC).

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#123] opened 2015-05-21 11:53 UTC
I created pipeline with csv file as tabular data. 
Problems: 
a) 2 primary keys are necessary
b) No preview for Rest API source is available
c) Base API URL is invalid, not clickable

These apply both for ODN/IC and ODN/PC

TCID: ODN-79:Retrieving data via REST API
TCID: ODN-78:Retrieving public data from a dataset via REST API

**Comment by skrchnavy** [comment] 2015-06-01 14:43
@eea71 do we have a pipeline? Or could you provide list of DPUs that were used to publish these data and important configuration?
Shouldn't we split this issue into separate problems?

**Comment by mvi-eea-sk** [comment] 2015-06-24 09:36
I assume relationToCkan or relationalDiffToCkan DPU was used as loader
a) don't know ...
b) related and fixed in #154
c) the problem is, that the link to datastore resource is relative:
/internalcatalog/datastore/dump/{here is the resource id}
in the template for resource there is check if the url is valid. the relative url doesn't pass this check. So the url is made not to be clickable and even the 'Download' button is not showed

@skrchnavy possible solution for c):
1) make it so that datastore plugin generates the full url <- simple and most appropriate change, but I have to make the change in core CKAN
2) remove the check from the template in core CKAN (edem does this, but for us the least desirable choice)
2) remove the check from the template in each of our themes

**Comment by hanecak** [comment] 2016-04-14 19:41
In an attempt to clean-up our backlog, I'm closing this as "wont fix" given that:

1. bug is truly old (we're supporting only most recent minor release, i.e. as of ODN 1.2.5, we're supporting 1.2.x, not older)
2. this behaviour is from upstream (CKAN), so if it is deemed a bug again, we will raise it with upstream

Having said that, whoever is negatively affected by this again in the future, please reopen this.

**Closed by hanecak** 2016-04-14 19:41 UTC
Labels: priority: Normal, severity: bug, status: needs discussion
