### ISSUE TITLE
Error in sed when upgrading to 1.0.3

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#158] opened 2015-06-30 07:01 UTC
When I upgrade from v1.0.2 to v1.0.3 using `sudo apt-get upgrade odn-simple`, an error in `sed` is reported:

```
>> set_ckan_internal_api: xpWxvnsU6fDPk53wAL8Ul0k1IDiQbM78
sed: -e expression #1, char 96: unterminated `s' command
dpkg: error processing odn-simple (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 odn-simple
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Jan-Marcek** [comment] 2015-06-30 09:22
@jindrichmynarz I can't reproduce even by calling same token. Please provide /var/log/apt/*

**Comment by Jan-Marcek** [comment] 2015-06-30 12:43
It seems that you installed strange version of odn-simple.
your postinstall of odn-simple : from ``` dpkg-deb -e /var/cache/apt/archives/odn-simple_1.0.3_all.deb /tmp/out``` which comes from  https://github.com/OpenDataNode/odn-box/commit/24ab372b72fd0fa22dcdb4ad23cdbd7b65b1e603
```
set_ckans_api() {
    echo ">> set_ckan_internal_api: "$1
    API_TOKEN=$1
    BACKEND_PROPS=/etc/unifiedviews/backend-config.properties

    # if token was previously set then we use it
    if grep -q "org.opendatanode.CKAN.secret.token" $BACKEND_PROPS ; then
      TOKEN_BACKEND=`cat $BACKEND_PROPS | grep -Po  'org.opendatanode.CKAN.secret.token = \K\w+'`
    fi

    if [ "$TOKEN_BACKEND" != "" ]; then
        API_TOKEN=$TOKEN_BACKEND
    fi

     sed --in-place \
        -e "s/ckan.auth.internal_api.token.*/ckan.auth.internal_api.token = ${API_TOKEN}/" \
         /etc/odn-simple/odn-ckan-ic/production.ini

    echo "token: ${API_TOKEN}"

    echo "<< "
}
```


The version of odn-simple in https://github.com/OpenDataNode/odn-box/commit/24ab372b72fd0fa22dcdb4ad23cdbd7b65b1e603 is not 1.0.3. 

You haven't done ```apt-get update``` according logs.
Please, could you do ```apt-get update && apt-get upgrade odn-simple``` I believe it going to work.

**Comment by jindrichmynarz** [comment] 2015-06-30 12:54
I have done `apt-get update`. Now, I executed `apt-get update && apt-get upgrade odn-simple` and got the same error.

**Comment by Jan-Marcek** [comment] 2015-06-30 13:57
OK :) there is two mistakes . 

The first - there is small bug: a function - https://github.com/OpenDataNode/odn-box/blob/ODN_v1.0.3/debian/odn-simple.postinst#L217 extracts: ```LdZJCSvxC2ciVkhcKlNyUmfjqvsOzX7L 8dwCle1iduagLpr1FfIJGwAsfFfmFddr ``` - bug in regexp. -  it is fixed by - https://github.com/OpenDataNode/odn-box/commit/540ade967c16898f961555d496789cb9e78a8f36


It is all because ```/etc/unifiedviews/backend.properties``` was in a "inconsistent state" where was more commented properties:
```
#org.opendatanode.CKAN.secret.token = LdZJCSvxC2ciVkhcKlNyUmfjqvsOzX7L 
....
org.opendatanode.CKAN.secret.token = 8dwCle1iduagLpr1FfIJGwAsfFfmFddr 
```
and it extracts both of them which is wrong.

The second:
Master was not merge to develop: fixed by https://github.com/OpenDataNode/odn-box/commit/13e693e74f572c77692577073be7f9a28e09ea22 . Why this happened is unclear - probably the merge conflict. 
That's why I though that you must have strange version of odn-simple.

@jindrichmynarz I removed the commented properties then I tried to install via ```apt-get update && apt-get upgrade odn-simple``` and it worked. Thank you for the report.

**Closed** 2015-06-30 14:00 UTC
Labels: priority: High, severity: bug, status: in progress
